// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package DoorController;

public interface IntercomCallResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntercomCallResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string callResponse = 1;</code>
   */
  java.lang.String getCallResponse();
  /**
   * <code>string callResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getCallResponseBytes();
}
