// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package DoorController;

public interface IntercomAnswerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IntercomAnswerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string answerResponse = 1;</code>
   */
  java.lang.String getAnswerResponse();
  /**
   * <code>string answerResponse = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnswerResponseBytes();
}
