// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package DoorController;

public interface OneWayCommunicationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OneWayCommunicationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool buttonHeld = 1;</code>
   */
  boolean getButtonHeld();
}
