// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package DoorController;

public interface OneWayCommunicationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OneWayCommunicationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string channelStatus = 1;</code>
   */
  java.lang.String getChannelStatus();
  /**
   * <code>string channelStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelStatusBytes();
}
