// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package Service2;

public interface CameraAdjustmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraAdjustmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cameraPosition = 1;</code>
   */
  java.lang.String getCameraPosition();
  /**
   * <code>string cameraPosition = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraPositionBytes();
}
