// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package Service2;

public interface CameraAutomationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraAutomationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cameraDirection = 1;</code>
   */
  java.lang.String getCameraDirection();
  /**
   * <code>string cameraDirection = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraDirectionBytes();
}
