// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package Service2;

public interface CameraAdjustmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraAdjustmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cameraID = 1;</code>
   */
  java.lang.String getCameraID();
  /**
   * <code>string cameraID = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIDBytes();

  /**
   * <code>string cameraDirection = 2;</code>
   */
  java.lang.String getCameraDirection();
  /**
   * <code>string cameraDirection = 2;</code>
   */
  com.google.protobuf.ByteString
      getCameraDirectionBytes();

  /**
   * <code>bool cameraBeingControlled = 3;</code>
   */
  boolean getCameraBeingControlled();
}
