// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package Service2;

/**
 * Protobuf type {@code CameraAdjustmentRequest}
 */
public  final class CameraAdjustmentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CameraAdjustmentRequest)
    CameraAdjustmentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CameraAdjustmentRequest.newBuilder() to construct.
  private CameraAdjustmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CameraAdjustmentRequest() {
    cameraID_ = "";
    cameraDirection_ = "";
    cameraBeingControlled_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CameraAdjustmentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cameraID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cameraDirection_ = s;
            break;
          }
          case 24: {

            cameraBeingControlled_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Service2.CameraControlsImpl.internal_static_CameraAdjustmentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Service2.CameraControlsImpl.internal_static_CameraAdjustmentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Service2.CameraAdjustmentRequest.class, Service2.CameraAdjustmentRequest.Builder.class);
  }

  public static final int CAMERAID_FIELD_NUMBER = 1;
  private volatile java.lang.Object cameraID_;
  /**
   * <code>string cameraID = 1;</code>
   */
  public java.lang.String getCameraID() {
    java.lang.Object ref = cameraID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cameraID_ = s;
      return s;
    }
  }
  /**
   * <code>string cameraID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCameraIDBytes() {
    java.lang.Object ref = cameraID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cameraID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAMERADIRECTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object cameraDirection_;
  /**
   * <code>string cameraDirection = 2;</code>
   */
  public java.lang.String getCameraDirection() {
    java.lang.Object ref = cameraDirection_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cameraDirection_ = s;
      return s;
    }
  }
  /**
   * <code>string cameraDirection = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCameraDirectionBytes() {
    java.lang.Object ref = cameraDirection_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cameraDirection_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAMERABEINGCONTROLLED_FIELD_NUMBER = 3;
  private boolean cameraBeingControlled_;
  /**
   * <code>bool cameraBeingControlled = 3;</code>
   */
  public boolean getCameraBeingControlled() {
    return cameraBeingControlled_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCameraIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cameraID_);
    }
    if (!getCameraDirectionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cameraDirection_);
    }
    if (cameraBeingControlled_ != false) {
      output.writeBool(3, cameraBeingControlled_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCameraIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cameraID_);
    }
    if (!getCameraDirectionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cameraDirection_);
    }
    if (cameraBeingControlled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, cameraBeingControlled_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Service2.CameraAdjustmentRequest)) {
      return super.equals(obj);
    }
    Service2.CameraAdjustmentRequest other = (Service2.CameraAdjustmentRequest) obj;

    boolean result = true;
    result = result && getCameraID()
        .equals(other.getCameraID());
    result = result && getCameraDirection()
        .equals(other.getCameraDirection());
    result = result && (getCameraBeingControlled()
        == other.getCameraBeingControlled());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CAMERAID_FIELD_NUMBER;
    hash = (53 * hash) + getCameraID().hashCode();
    hash = (37 * hash) + CAMERADIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + getCameraDirection().hashCode();
    hash = (37 * hash) + CAMERABEINGCONTROLLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCameraBeingControlled());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Service2.CameraAdjustmentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Service2.CameraAdjustmentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Service2.CameraAdjustmentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Service2.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Service2.CameraAdjustmentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CameraAdjustmentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CameraAdjustmentRequest)
      Service2.CameraAdjustmentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service2.CameraControlsImpl.internal_static_CameraAdjustmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service2.CameraControlsImpl.internal_static_CameraAdjustmentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Service2.CameraAdjustmentRequest.class, Service2.CameraAdjustmentRequest.Builder.class);
    }

    // Construct using Service2.CameraAdjustmentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cameraID_ = "";

      cameraDirection_ = "";

      cameraBeingControlled_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Service2.CameraControlsImpl.internal_static_CameraAdjustmentRequest_descriptor;
    }

    @java.lang.Override
    public Service2.CameraAdjustmentRequest getDefaultInstanceForType() {
      return Service2.CameraAdjustmentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public Service2.CameraAdjustmentRequest build() {
      Service2.CameraAdjustmentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Service2.CameraAdjustmentRequest buildPartial() {
      Service2.CameraAdjustmentRequest result = new Service2.CameraAdjustmentRequest(this);
      result.cameraID_ = cameraID_;
      result.cameraDirection_ = cameraDirection_;
      result.cameraBeingControlled_ = cameraBeingControlled_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Service2.CameraAdjustmentRequest) {
        return mergeFrom((Service2.CameraAdjustmentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Service2.CameraAdjustmentRequest other) {
      if (other == Service2.CameraAdjustmentRequest.getDefaultInstance()) return this;
      if (!other.getCameraID().isEmpty()) {
        cameraID_ = other.cameraID_;
        onChanged();
      }
      if (!other.getCameraDirection().isEmpty()) {
        cameraDirection_ = other.cameraDirection_;
        onChanged();
      }
      if (other.getCameraBeingControlled() != false) {
        setCameraBeingControlled(other.getCameraBeingControlled());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Service2.CameraAdjustmentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Service2.CameraAdjustmentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cameraID_ = "";
    /**
     * <code>string cameraID = 1;</code>
     */
    public java.lang.String getCameraID() {
      java.lang.Object ref = cameraID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cameraID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCameraIDBytes() {
      java.lang.Object ref = cameraID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cameraID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public Builder setCameraID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cameraID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public Builder clearCameraID() {
      
      cameraID_ = getDefaultInstance().getCameraID();
      onChanged();
      return this;
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public Builder setCameraIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cameraID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cameraDirection_ = "";
    /**
     * <code>string cameraDirection = 2;</code>
     */
    public java.lang.String getCameraDirection() {
      java.lang.Object ref = cameraDirection_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cameraDirection_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cameraDirection = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCameraDirectionBytes() {
      java.lang.Object ref = cameraDirection_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cameraDirection_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cameraDirection = 2;</code>
     */
    public Builder setCameraDirection(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cameraDirection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cameraDirection = 2;</code>
     */
    public Builder clearCameraDirection() {
      
      cameraDirection_ = getDefaultInstance().getCameraDirection();
      onChanged();
      return this;
    }
    /**
     * <code>string cameraDirection = 2;</code>
     */
    public Builder setCameraDirectionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cameraDirection_ = value;
      onChanged();
      return this;
    }

    private boolean cameraBeingControlled_ ;
    /**
     * <code>bool cameraBeingControlled = 3;</code>
     */
    public boolean getCameraBeingControlled() {
      return cameraBeingControlled_;
    }
    /**
     * <code>bool cameraBeingControlled = 3;</code>
     */
    public Builder setCameraBeingControlled(boolean value) {
      
      cameraBeingControlled_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool cameraBeingControlled = 3;</code>
     */
    public Builder clearCameraBeingControlled() {
      
      cameraBeingControlled_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CameraAdjustmentRequest)
  }

  // @@protoc_insertion_point(class_scope:CameraAdjustmentRequest)
  private static final Service2.CameraAdjustmentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Service2.CameraAdjustmentRequest();
  }

  public static Service2.CameraAdjustmentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CameraAdjustmentRequest>
      PARSER = new com.google.protobuf.AbstractParser<CameraAdjustmentRequest>() {
    @java.lang.Override
    public CameraAdjustmentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CameraAdjustmentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CameraAdjustmentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CameraAdjustmentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Service2.CameraAdjustmentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

