// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package Service3;

public final class AlarmControlsImpl {
  private AlarmControlsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ManualAlarmRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ManualAlarmRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ManualAlarmResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ManualAlarmResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FireSuppressionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FireSuppressionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FireSuppressionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FireSuppressionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServicesCallRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServicesCallRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyServicesCallResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyServicesCallResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Service3.proto\"=\n\022ManualAlarmRequest\022\017" +
      "\n\007alarmID\030\001 \001(\t\022\026\n\016alarmTriggered\030\002 \001(\010\"" +
      "Y\n\023ManualAlarmResponse\022!\n\031activateEmerge" +
      "ncyLighting\030\001 \001(\t\022\037\n\027activateEmergencySi" +
      "rens\030\002 \001(\t\"B\n\026FireSuppressionRequest\022\020\n\010" +
      "sensorID\030\001 \001(\t\022\026\n\016hazardDetected\030\002 \001(\010\"]" +
      "\n\027FireSuppressionResponse\022!\n\031activateEme" +
      "rgencyLighting\030\001 \001(\t\022\037\n\027activateEmergenc" +
      "ySirens\030\002 \001(\t\"6\n\034EmergencyServicesCallRe" +
      "quest\022\026\n\016alarmTriggered\030\001 \001(\010\"9\n\035Emergen" +
      "cyServicesCallResponse\022\030\n\020callConfirmati" +
      "on\030\001 \001(\t2\354\001\n\010Service3\022<\n\013manualAlarm\022\023.M" +
      "anualAlarmRequest\032\024.ManualAlarmResponse\"" +
      "\0000\001\022H\n\017fireSuppression\022\027.FireSuppression" +
      "Request\032\030.FireSuppressionResponse\"\0000\001\022X\n" +
      "\025emergencyServicesCall\022\035.EmergencyServic" +
      "esCallRequest\032\036.EmergencyServicesCallRes" +
      "ponse\"\000B\037\n\010Service3B\021AlarmControlsImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ManualAlarmRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ManualAlarmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ManualAlarmRequest_descriptor,
        new java.lang.String[] { "AlarmID", "AlarmTriggered", });
    internal_static_ManualAlarmResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ManualAlarmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ManualAlarmResponse_descriptor,
        new java.lang.String[] { "ActivateEmergencyLighting", "ActivateEmergencySirens", });
    internal_static_FireSuppressionRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FireSuppressionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FireSuppressionRequest_descriptor,
        new java.lang.String[] { "SensorID", "HazardDetected", });
    internal_static_FireSuppressionResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_FireSuppressionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FireSuppressionResponse_descriptor,
        new java.lang.String[] { "ActivateEmergencyLighting", "ActivateEmergencySirens", });
    internal_static_EmergencyServicesCallRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EmergencyServicesCallRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServicesCallRequest_descriptor,
        new java.lang.String[] { "AlarmTriggered", });
    internal_static_EmergencyServicesCallResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_EmergencyServicesCallResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyServicesCallResponse_descriptor,
        new java.lang.String[] { "CallConfirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
