// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package Service3;

public interface EmergencyServicesCallResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyServicesCallResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string callConfirmation = 1;</code>
   */
  java.lang.String getCallConfirmation();
  /**
   * <code>string callConfirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getCallConfirmationBytes();
}
