// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package Service3;

/**
 * Protobuf type {@code FireSuppressionRequest}
 */
public  final class FireSuppressionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FireSuppressionRequest)
    FireSuppressionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FireSuppressionRequest.newBuilder() to construct.
  private FireSuppressionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FireSuppressionRequest() {
    sensorID_ = "";
    hazardDetected_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FireSuppressionRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sensorID_ = s;
            break;
          }
          case 16: {

            hazardDetected_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Service3.AlarmControlsImpl.internal_static_FireSuppressionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Service3.AlarmControlsImpl.internal_static_FireSuppressionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Service3.FireSuppressionRequest.class, Service3.FireSuppressionRequest.Builder.class);
  }

  public static final int SENSORID_FIELD_NUMBER = 1;
  private volatile java.lang.Object sensorID_;
  /**
   * <code>string sensorID = 1;</code>
   */
  public java.lang.String getSensorID() {
    java.lang.Object ref = sensorID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sensorID_ = s;
      return s;
    }
  }
  /**
   * <code>string sensorID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSensorIDBytes() {
    java.lang.Object ref = sensorID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sensorID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HAZARDDETECTED_FIELD_NUMBER = 2;
  private boolean hazardDetected_;
  /**
   * <code>bool hazardDetected = 2;</code>
   */
  public boolean getHazardDetected() {
    return hazardDetected_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSensorIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sensorID_);
    }
    if (hazardDetected_ != false) {
      output.writeBool(2, hazardDetected_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSensorIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sensorID_);
    }
    if (hazardDetected_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, hazardDetected_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Service3.FireSuppressionRequest)) {
      return super.equals(obj);
    }
    Service3.FireSuppressionRequest other = (Service3.FireSuppressionRequest) obj;

    boolean result = true;
    result = result && getSensorID()
        .equals(other.getSensorID());
    result = result && (getHazardDetected()
        == other.getHazardDetected());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENSORID_FIELD_NUMBER;
    hash = (53 * hash) + getSensorID().hashCode();
    hash = (37 * hash) + HAZARDDETECTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHazardDetected());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Service3.FireSuppressionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service3.FireSuppressionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service3.FireSuppressionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service3.FireSuppressionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service3.FireSuppressionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service3.FireSuppressionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service3.FireSuppressionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Service3.FireSuppressionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Service3.FireSuppressionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Service3.FireSuppressionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Service3.FireSuppressionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Service3.FireSuppressionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Service3.FireSuppressionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FireSuppressionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FireSuppressionRequest)
      Service3.FireSuppressionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service3.AlarmControlsImpl.internal_static_FireSuppressionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service3.AlarmControlsImpl.internal_static_FireSuppressionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Service3.FireSuppressionRequest.class, Service3.FireSuppressionRequest.Builder.class);
    }

    // Construct using Service3.FireSuppressionRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sensorID_ = "";

      hazardDetected_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Service3.AlarmControlsImpl.internal_static_FireSuppressionRequest_descriptor;
    }

    @java.lang.Override
    public Service3.FireSuppressionRequest getDefaultInstanceForType() {
      return Service3.FireSuppressionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public Service3.FireSuppressionRequest build() {
      Service3.FireSuppressionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Service3.FireSuppressionRequest buildPartial() {
      Service3.FireSuppressionRequest result = new Service3.FireSuppressionRequest(this);
      result.sensorID_ = sensorID_;
      result.hazardDetected_ = hazardDetected_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Service3.FireSuppressionRequest) {
        return mergeFrom((Service3.FireSuppressionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Service3.FireSuppressionRequest other) {
      if (other == Service3.FireSuppressionRequest.getDefaultInstance()) return this;
      if (!other.getSensorID().isEmpty()) {
        sensorID_ = other.sensorID_;
        onChanged();
      }
      if (other.getHazardDetected() != false) {
        setHazardDetected(other.getHazardDetected());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Service3.FireSuppressionRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Service3.FireSuppressionRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sensorID_ = "";
    /**
     * <code>string sensorID = 1;</code>
     */
    public java.lang.String getSensorID() {
      java.lang.Object ref = sensorID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sensorID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sensorID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSensorIDBytes() {
      java.lang.Object ref = sensorID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sensorID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sensorID = 1;</code>
     */
    public Builder setSensorID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sensorID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sensorID = 1;</code>
     */
    public Builder clearSensorID() {
      
      sensorID_ = getDefaultInstance().getSensorID();
      onChanged();
      return this;
    }
    /**
     * <code>string sensorID = 1;</code>
     */
    public Builder setSensorIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sensorID_ = value;
      onChanged();
      return this;
    }

    private boolean hazardDetected_ ;
    /**
     * <code>bool hazardDetected = 2;</code>
     */
    public boolean getHazardDetected() {
      return hazardDetected_;
    }
    /**
     * <code>bool hazardDetected = 2;</code>
     */
    public Builder setHazardDetected(boolean value) {
      
      hazardDetected_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool hazardDetected = 2;</code>
     */
    public Builder clearHazardDetected() {
      
      hazardDetected_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FireSuppressionRequest)
  }

  // @@protoc_insertion_point(class_scope:FireSuppressionRequest)
  private static final Service3.FireSuppressionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Service3.FireSuppressionRequest();
  }

  public static Service3.FireSuppressionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FireSuppressionRequest>
      PARSER = new com.google.protobuf.AbstractParser<FireSuppressionRequest>() {
    @java.lang.Override
    public FireSuppressionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FireSuppressionRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FireSuppressionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FireSuppressionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Service3.FireSuppressionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

