// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package Service3;

public interface FireSuppressionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FireSuppressionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sensorID = 1;</code>
   */
  java.lang.String getSensorID();
  /**
   * <code>string sensorID = 1;</code>
   */
  com.google.protobuf.ByteString
      getSensorIDBytes();

  /**
   * <code>bool hazardDetected = 2;</code>
   */
  boolean getHazardDetected();
}
