// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package Service3;

/**
 * Protobuf type {@code FireSuppressionResponse}
 */
public  final class FireSuppressionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FireSuppressionResponse)
    FireSuppressionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FireSuppressionResponse.newBuilder() to construct.
  private FireSuppressionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FireSuppressionResponse() {
    activateEmergencyLighting_ = "";
    activateEmergencySirens_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FireSuppressionResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            activateEmergencyLighting_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            activateEmergencySirens_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Service3.AlarmControlsImpl.internal_static_FireSuppressionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Service3.AlarmControlsImpl.internal_static_FireSuppressionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Service3.FireSuppressionResponse.class, Service3.FireSuppressionResponse.Builder.class);
  }

  public static final int ACTIVATEEMERGENCYLIGHTING_FIELD_NUMBER = 1;
  private volatile java.lang.Object activateEmergencyLighting_;
  /**
   * <code>string activateEmergencyLighting = 1;</code>
   */
  public java.lang.String getActivateEmergencyLighting() {
    java.lang.Object ref = activateEmergencyLighting_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      activateEmergencyLighting_ = s;
      return s;
    }
  }
  /**
   * <code>string activateEmergencyLighting = 1;</code>
   */
  public com.google.protobuf.ByteString
      getActivateEmergencyLightingBytes() {
    java.lang.Object ref = activateEmergencyLighting_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      activateEmergencyLighting_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTIVATEEMERGENCYSIRENS_FIELD_NUMBER = 2;
  private volatile java.lang.Object activateEmergencySirens_;
  /**
   * <code>string activateEmergencySirens = 2;</code>
   */
  public java.lang.String getActivateEmergencySirens() {
    java.lang.Object ref = activateEmergencySirens_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      activateEmergencySirens_ = s;
      return s;
    }
  }
  /**
   * <code>string activateEmergencySirens = 2;</code>
   */
  public com.google.protobuf.ByteString
      getActivateEmergencySirensBytes() {
    java.lang.Object ref = activateEmergencySirens_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      activateEmergencySirens_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getActivateEmergencyLightingBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, activateEmergencyLighting_);
    }
    if (!getActivateEmergencySirensBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, activateEmergencySirens_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getActivateEmergencyLightingBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, activateEmergencyLighting_);
    }
    if (!getActivateEmergencySirensBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, activateEmergencySirens_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Service3.FireSuppressionResponse)) {
      return super.equals(obj);
    }
    Service3.FireSuppressionResponse other = (Service3.FireSuppressionResponse) obj;

    boolean result = true;
    result = result && getActivateEmergencyLighting()
        .equals(other.getActivateEmergencyLighting());
    result = result && getActivateEmergencySirens()
        .equals(other.getActivateEmergencySirens());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTIVATEEMERGENCYLIGHTING_FIELD_NUMBER;
    hash = (53 * hash) + getActivateEmergencyLighting().hashCode();
    hash = (37 * hash) + ACTIVATEEMERGENCYSIRENS_FIELD_NUMBER;
    hash = (53 * hash) + getActivateEmergencySirens().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Service3.FireSuppressionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service3.FireSuppressionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service3.FireSuppressionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service3.FireSuppressionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service3.FireSuppressionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Service3.FireSuppressionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Service3.FireSuppressionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Service3.FireSuppressionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Service3.FireSuppressionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Service3.FireSuppressionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Service3.FireSuppressionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Service3.FireSuppressionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Service3.FireSuppressionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FireSuppressionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FireSuppressionResponse)
      Service3.FireSuppressionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Service3.AlarmControlsImpl.internal_static_FireSuppressionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Service3.AlarmControlsImpl.internal_static_FireSuppressionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Service3.FireSuppressionResponse.class, Service3.FireSuppressionResponse.Builder.class);
    }

    // Construct using Service3.FireSuppressionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      activateEmergencyLighting_ = "";

      activateEmergencySirens_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Service3.AlarmControlsImpl.internal_static_FireSuppressionResponse_descriptor;
    }

    @java.lang.Override
    public Service3.FireSuppressionResponse getDefaultInstanceForType() {
      return Service3.FireSuppressionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public Service3.FireSuppressionResponse build() {
      Service3.FireSuppressionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Service3.FireSuppressionResponse buildPartial() {
      Service3.FireSuppressionResponse result = new Service3.FireSuppressionResponse(this);
      result.activateEmergencyLighting_ = activateEmergencyLighting_;
      result.activateEmergencySirens_ = activateEmergencySirens_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Service3.FireSuppressionResponse) {
        return mergeFrom((Service3.FireSuppressionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Service3.FireSuppressionResponse other) {
      if (other == Service3.FireSuppressionResponse.getDefaultInstance()) return this;
      if (!other.getActivateEmergencyLighting().isEmpty()) {
        activateEmergencyLighting_ = other.activateEmergencyLighting_;
        onChanged();
      }
      if (!other.getActivateEmergencySirens().isEmpty()) {
        activateEmergencySirens_ = other.activateEmergencySirens_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Service3.FireSuppressionResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Service3.FireSuppressionResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object activateEmergencyLighting_ = "";
    /**
     * <code>string activateEmergencyLighting = 1;</code>
     */
    public java.lang.String getActivateEmergencyLighting() {
      java.lang.Object ref = activateEmergencyLighting_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activateEmergencyLighting_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string activateEmergencyLighting = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActivateEmergencyLightingBytes() {
      java.lang.Object ref = activateEmergencyLighting_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activateEmergencyLighting_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string activateEmergencyLighting = 1;</code>
     */
    public Builder setActivateEmergencyLighting(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      activateEmergencyLighting_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string activateEmergencyLighting = 1;</code>
     */
    public Builder clearActivateEmergencyLighting() {
      
      activateEmergencyLighting_ = getDefaultInstance().getActivateEmergencyLighting();
      onChanged();
      return this;
    }
    /**
     * <code>string activateEmergencyLighting = 1;</code>
     */
    public Builder setActivateEmergencyLightingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      activateEmergencyLighting_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object activateEmergencySirens_ = "";
    /**
     * <code>string activateEmergencySirens = 2;</code>
     */
    public java.lang.String getActivateEmergencySirens() {
      java.lang.Object ref = activateEmergencySirens_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activateEmergencySirens_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string activateEmergencySirens = 2;</code>
     */
    public com.google.protobuf.ByteString
        getActivateEmergencySirensBytes() {
      java.lang.Object ref = activateEmergencySirens_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activateEmergencySirens_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string activateEmergencySirens = 2;</code>
     */
    public Builder setActivateEmergencySirens(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      activateEmergencySirens_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string activateEmergencySirens = 2;</code>
     */
    public Builder clearActivateEmergencySirens() {
      
      activateEmergencySirens_ = getDefaultInstance().getActivateEmergencySirens();
      onChanged();
      return this;
    }
    /**
     * <code>string activateEmergencySirens = 2;</code>
     */
    public Builder setActivateEmergencySirensBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      activateEmergencySirens_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FireSuppressionResponse)
  }

  // @@protoc_insertion_point(class_scope:FireSuppressionResponse)
  private static final Service3.FireSuppressionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Service3.FireSuppressionResponse();
  }

  public static Service3.FireSuppressionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FireSuppressionResponse>
      PARSER = new com.google.protobuf.AbstractParser<FireSuppressionResponse>() {
    @java.lang.Override
    public FireSuppressionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FireSuppressionResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FireSuppressionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FireSuppressionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Service3.FireSuppressionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

