// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package Service3;

public interface FireSuppressionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FireSuppressionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string activateEmergencyLighting = 1;</code>
   */
  java.lang.String getActivateEmergencyLighting();
  /**
   * <code>string activateEmergencyLighting = 1;</code>
   */
  com.google.protobuf.ByteString
      getActivateEmergencyLightingBytes();

  /**
   * <code>string activateEmergencySirens = 2;</code>
   */
  java.lang.String getActivateEmergencySirens();
  /**
   * <code>string activateEmergencySirens = 2;</code>
   */
  com.google.protobuf.ByteString
      getActivateEmergencySirensBytes();
}
