// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package Service3;

public interface ManualAlarmRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ManualAlarmRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alarmID = 1;</code>
   */
  java.lang.String getAlarmID();
  /**
   * <code>string alarmID = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlarmIDBytes();

  /**
   * <code>bool alarmTriggered = 2;</code>
   */
  boolean getAlarmTriggered();
}
