// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package CameraController;

public interface CameraAutomationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraAutomationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string automatedCameraID = 1;</code>
   */
  java.lang.String getAutomatedCameraID();
  /**
   * <code>string automatedCameraID = 1;</code>
   */
  com.google.protobuf.ByteString
      getAutomatedCameraIDBytes();

  /**
   * <code>string cameraPosition = 2;</code>
   */
  java.lang.String getCameraPosition();
  /**
   * <code>string cameraPosition = 2;</code>
   */
  com.google.protobuf.ByteString
      getCameraPositionBytes();

  /**
   * <code>string locationOfMovement = 3;</code>
   */
  java.lang.String getLocationOfMovement();
  /**
   * <code>string locationOfMovement = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationOfMovementBytes();
}
