// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package CameraController;

public interface CameraAdjustmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraAdjustmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cameraID = 1;</code>
   */
  java.lang.String getCameraID();
  /**
   * <code>string cameraID = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraIDBytes();

  /**
   * <code>int32 cameraPositionX = 2;</code>
   */
  int getCameraPositionX();

  /**
   * <code>int32 cameraPositionY = 3;</code>
   */
  int getCameraPositionY();

  /**
   * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 4;</code>
   */
  int getCameraDirectionValue();
  /**
   * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 4;</code>
   */
  CameraController.CameraAdjustmentRequest.CameraDirection getCameraDirection();
}
