// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package CameraController;

/**
 * Protobuf type {@code CameraAdjustmentRequest}
 */
public  final class CameraAdjustmentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CameraAdjustmentRequest)
    CameraAdjustmentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CameraAdjustmentRequest.newBuilder() to construct.
  private CameraAdjustmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CameraAdjustmentRequest() {
    cameraID_ = "";
    cameraPosition_ = "";
    cameraDirection_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CameraAdjustmentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            cameraID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cameraPosition_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            cameraDirection_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CameraController.CameraControlsImpl.internal_static_CameraAdjustmentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CameraController.CameraControlsImpl.internal_static_CameraAdjustmentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CameraController.CameraAdjustmentRequest.class, CameraController.CameraAdjustmentRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code CameraAdjustmentRequest.CameraDirection}
   */
  public enum CameraDirection
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UP = 0;</code>
     */
    UP(0),
    /**
     * <code>DOWN = 1;</code>
     */
    DOWN(1),
    /**
     * <code>LEFT = 2;</code>
     */
    LEFT(2),
    /**
     * <code>RIGHT = 3;</code>
     */
    RIGHT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UP = 0;</code>
     */
    public static final int UP_VALUE = 0;
    /**
     * <code>DOWN = 1;</code>
     */
    public static final int DOWN_VALUE = 1;
    /**
     * <code>LEFT = 2;</code>
     */
    public static final int LEFT_VALUE = 2;
    /**
     * <code>RIGHT = 3;</code>
     */
    public static final int RIGHT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CameraDirection valueOf(int value) {
      return forNumber(value);
    }

    public static CameraDirection forNumber(int value) {
      switch (value) {
        case 0: return UP;
        case 1: return DOWN;
        case 2: return LEFT;
        case 3: return RIGHT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CameraDirection>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CameraDirection> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CameraDirection>() {
            public CameraDirection findValueByNumber(int number) {
              return CameraDirection.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CameraController.CameraAdjustmentRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final CameraDirection[] VALUES = values();

    public static CameraDirection valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CameraDirection(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CameraAdjustmentRequest.CameraDirection)
  }

  public static final int CAMERAID_FIELD_NUMBER = 1;
  private volatile java.lang.Object cameraID_;
  /**
   * <code>string cameraID = 1;</code>
   */
  public java.lang.String getCameraID() {
    java.lang.Object ref = cameraID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cameraID_ = s;
      return s;
    }
  }
  /**
   * <code>string cameraID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCameraIDBytes() {
    java.lang.Object ref = cameraID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cameraID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAMERAPOSITION_FIELD_NUMBER = 2;
  private volatile java.lang.Object cameraPosition_;
  /**
   * <code>string cameraPosition = 2;</code>
   */
  public java.lang.String getCameraPosition() {
    java.lang.Object ref = cameraPosition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cameraPosition_ = s;
      return s;
    }
  }
  /**
   * <code>string cameraPosition = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCameraPositionBytes() {
    java.lang.Object ref = cameraPosition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cameraPosition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAMERADIRECTION_FIELD_NUMBER = 3;
  private int cameraDirection_;
  /**
   * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 3;</code>
   */
  public int getCameraDirectionValue() {
    return cameraDirection_;
  }
  /**
   * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 3;</code>
   */
  public CameraController.CameraAdjustmentRequest.CameraDirection getCameraDirection() {
    @SuppressWarnings("deprecation")
    CameraController.CameraAdjustmentRequest.CameraDirection result = CameraController.CameraAdjustmentRequest.CameraDirection.valueOf(cameraDirection_);
    return result == null ? CameraController.CameraAdjustmentRequest.CameraDirection.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCameraIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cameraID_);
    }
    if (!getCameraPositionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cameraPosition_);
    }
    if (cameraDirection_ != CameraController.CameraAdjustmentRequest.CameraDirection.UP.getNumber()) {
      output.writeEnum(3, cameraDirection_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCameraIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cameraID_);
    }
    if (!getCameraPositionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cameraPosition_);
    }
    if (cameraDirection_ != CameraController.CameraAdjustmentRequest.CameraDirection.UP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, cameraDirection_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CameraController.CameraAdjustmentRequest)) {
      return super.equals(obj);
    }
    CameraController.CameraAdjustmentRequest other = (CameraController.CameraAdjustmentRequest) obj;

    boolean result = true;
    result = result && getCameraID()
        .equals(other.getCameraID());
    result = result && getCameraPosition()
        .equals(other.getCameraPosition());
    result = result && cameraDirection_ == other.cameraDirection_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CAMERAID_FIELD_NUMBER;
    hash = (53 * hash) + getCameraID().hashCode();
    hash = (37 * hash) + CAMERAPOSITION_FIELD_NUMBER;
    hash = (53 * hash) + getCameraPosition().hashCode();
    hash = (37 * hash) + CAMERADIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + cameraDirection_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CameraController.CameraAdjustmentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CameraController.CameraAdjustmentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CameraController.CameraAdjustmentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CameraController.CameraAdjustmentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CameraController.CameraAdjustmentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CameraAdjustmentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CameraAdjustmentRequest)
      CameraController.CameraAdjustmentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CameraController.CameraControlsImpl.internal_static_CameraAdjustmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CameraController.CameraControlsImpl.internal_static_CameraAdjustmentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CameraController.CameraAdjustmentRequest.class, CameraController.CameraAdjustmentRequest.Builder.class);
    }

    // Construct using CameraController.CameraAdjustmentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cameraID_ = "";

      cameraPosition_ = "";

      cameraDirection_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CameraController.CameraControlsImpl.internal_static_CameraAdjustmentRequest_descriptor;
    }

    @java.lang.Override
    public CameraController.CameraAdjustmentRequest getDefaultInstanceForType() {
      return CameraController.CameraAdjustmentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public CameraController.CameraAdjustmentRequest build() {
      CameraController.CameraAdjustmentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public CameraController.CameraAdjustmentRequest buildPartial() {
      CameraController.CameraAdjustmentRequest result = new CameraController.CameraAdjustmentRequest(this);
      result.cameraID_ = cameraID_;
      result.cameraPosition_ = cameraPosition_;
      result.cameraDirection_ = cameraDirection_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CameraController.CameraAdjustmentRequest) {
        return mergeFrom((CameraController.CameraAdjustmentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CameraController.CameraAdjustmentRequest other) {
      if (other == CameraController.CameraAdjustmentRequest.getDefaultInstance()) return this;
      if (!other.getCameraID().isEmpty()) {
        cameraID_ = other.cameraID_;
        onChanged();
      }
      if (!other.getCameraPosition().isEmpty()) {
        cameraPosition_ = other.cameraPosition_;
        onChanged();
      }
      if (other.cameraDirection_ != 0) {
        setCameraDirectionValue(other.getCameraDirectionValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CameraController.CameraAdjustmentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CameraController.CameraAdjustmentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object cameraID_ = "";
    /**
     * <code>string cameraID = 1;</code>
     */
    public java.lang.String getCameraID() {
      java.lang.Object ref = cameraID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cameraID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCameraIDBytes() {
      java.lang.Object ref = cameraID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cameraID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public Builder setCameraID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cameraID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public Builder clearCameraID() {
      
      cameraID_ = getDefaultInstance().getCameraID();
      onChanged();
      return this;
    }
    /**
     * <code>string cameraID = 1;</code>
     */
    public Builder setCameraIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cameraID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cameraPosition_ = "";
    /**
     * <code>string cameraPosition = 2;</code>
     */
    public java.lang.String getCameraPosition() {
      java.lang.Object ref = cameraPosition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cameraPosition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cameraPosition = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCameraPositionBytes() {
      java.lang.Object ref = cameraPosition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cameraPosition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cameraPosition = 2;</code>
     */
    public Builder setCameraPosition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cameraPosition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cameraPosition = 2;</code>
     */
    public Builder clearCameraPosition() {
      
      cameraPosition_ = getDefaultInstance().getCameraPosition();
      onChanged();
      return this;
    }
    /**
     * <code>string cameraPosition = 2;</code>
     */
    public Builder setCameraPositionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cameraPosition_ = value;
      onChanged();
      return this;
    }

    private int cameraDirection_ = 0;
    /**
     * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 3;</code>
     */
    public int getCameraDirectionValue() {
      return cameraDirection_;
    }
    /**
     * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 3;</code>
     */
    public Builder setCameraDirectionValue(int value) {
      cameraDirection_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 3;</code>
     */
    public CameraController.CameraAdjustmentRequest.CameraDirection getCameraDirection() {
      @SuppressWarnings("deprecation")
      CameraController.CameraAdjustmentRequest.CameraDirection result = CameraController.CameraAdjustmentRequest.CameraDirection.valueOf(cameraDirection_);
      return result == null ? CameraController.CameraAdjustmentRequest.CameraDirection.UNRECOGNIZED : result;
    }
    /**
     * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 3;</code>
     */
    public Builder setCameraDirection(CameraController.CameraAdjustmentRequest.CameraDirection value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      cameraDirection_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.CameraAdjustmentRequest.CameraDirection cameraDirection = 3;</code>
     */
    public Builder clearCameraDirection() {
      
      cameraDirection_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CameraAdjustmentRequest)
  }

  // @@protoc_insertion_point(class_scope:CameraAdjustmentRequest)
  private static final CameraController.CameraAdjustmentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CameraController.CameraAdjustmentRequest();
  }

  public static CameraController.CameraAdjustmentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CameraAdjustmentRequest>
      PARSER = new com.google.protobuf.AbstractParser<CameraAdjustmentRequest>() {
    @java.lang.Override
    public CameraAdjustmentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CameraAdjustmentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CameraAdjustmentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CameraAdjustmentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public CameraController.CameraAdjustmentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

