// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package CameraController;

public interface CameraAutomationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CameraAutomationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cameraAutomation = 1;</code>
   */
  java.lang.String getCameraAutomation();
  /**
   * <code>string cameraAutomation = 1;</code>
   */
  com.google.protobuf.ByteString
      getCameraAutomationBytes();
}
