// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package CameraController;

public interface MotionDetectedResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MotionDetectedResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string detectionAlert = 1;</code>
   */
  java.lang.String getDetectionAlert();
  /**
   * <code>string detectionAlert = 1;</code>
   */
  com.google.protobuf.ByteString
      getDetectionAlertBytes();

  /**
   * <code>string motionLocation = 2;</code>
   */
  java.lang.String getMotionLocation();
  /**
   * <code>string motionLocation = 2;</code>
   */
  com.google.protobuf.ByteString
      getMotionLocationBytes();
}
