// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package CameraController;

public interface MotionDetectedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MotionDetectedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool motionedDetected = 1;</code>
   */
  boolean getMotionedDetected();
}
