// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service2.proto

package CameraController;

public interface MotionDetectedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MotionDetectedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string motionLocation = 1;</code>
   */
  java.lang.String getMotionLocation();
  /**
   * <code>string motionLocation = 1;</code>
   */
  com.google.protobuf.ByteString
      getMotionLocationBytes();
}
