// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package Service1;

public interface ScanSecurityBadgeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ScanSecurityBadgeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doorID = 1;</code>
   */
  java.lang.String getDoorID();
  /**
   * <code>string doorID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoorIDBytes();

  /**
   * <code>string badgeID = 2;</code>
   */
  java.lang.String getBadgeID();
  /**
   * <code>string badgeID = 2;</code>
   */
  com.google.protobuf.ByteString
      getBadgeIDBytes();
}
