// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package Service1;

public interface SecurityCodeEntryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SecurityCodeEntryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doorID = 1;</code>
   */
  java.lang.String getDoorID();
  /**
   * <code>string doorID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoorIDBytes();

  /**
   * <code>string securityCode = 2;</code>
   */
  java.lang.String getSecurityCode();
  /**
   * <code>string securityCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getSecurityCodeBytes();
}
