// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service1.proto

package Service1;

public interface SecurityCodeEntryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SecurityCodeEntryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool valid = 1;</code>
   */
  boolean getValid();
}
