// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service3.proto

package AlarmController;

public interface EmergencyServicesCallRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyServicesCallRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alarmTriggered = 1;</code>
   */
  java.lang.String getAlarmTriggered();
  /**
   * <code>string alarmTriggered = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlarmTriggeredBytes();
}
